DROP TABLE IF EXISTS requests, users, items, bookings, comments;

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGSERIAL NOT NULL,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT PK_CATEGORY PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGSERIAL NOT NULL,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,
  CONSTRAINT PK_LOCATION PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGSERIAL NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  eventId BIGINT NOT NULL,
  requesterId BIGINT NOT NULL,
  status VARCHAR(255) NOT NULL,
  CONSTRAINT PK_LOCATION PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGSERIAL NOT NULL,
  annotation VARCHAR(512),
  category_id BIGINT,
  description VARCHAR(512),
  event_date VARCHAR(255),
  location_id BIGINT,
  paid boolean,
  participant_limit BIGINT,
  request_moderation boolean,
  title VARCHAR(512),
  CONSTRAINT PK_EVENT PRIMARY KEY (id),
  CONSTRAINT EVENTS_CATEGORIES_ID_FK FOREIGN KEY (category_id) REFERENCES categories (ID) ON DELETE CASCADE,
  CONSTRAINT EVENTS_LOCATIONS_ID_FK FOREIGN KEY (location_id) REFERENCES locations (ID) ON DELETE CASCADE,
);