version: '3.1'
services:
  stats-server:
    build: stats-service/server
    container_name: stats-server-container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=zagloba
      - SPRING_DATASOURCE_PASSWORD=zagloba

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=zagloba
      - POSTGRES_PASSWORD=zagloba

  ewm-service:
    build: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=zagloba
      - SPRING_DATASOURCE_PASSWORD=zagloba

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=zagloba
      - POSTGRES_PASSWORD=zagloba
